
Parameters:
  IBKeyPair:
    Type: String
    Default: ""
  StackName:
    Type: String
    Default: ""
  VpcId:
    Type: String
    Default: ""
  SubnetId:
    Type: String
    Default: ""
  SGId:
    Type: String
    Default: ""
  BucketName:
    Type: String
    Default: ""

Mappings: 
  RegionMap: 
    us-east-1: 
      "ParentImage": "ami-0c5bf07e510b75b11"
    eu-west-1: 
      "ParentImage": "ami-08f51d843bf37ded6"
      
Conditions:
  EmptyIBKey: !Equals [ !Ref IBKeyPair, ""]
Resources:
  IBInstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - "ibguara3"

  InfrastructureConfigurationAll:
    Type: 'AWS::ImageBuilder::InfrastructureConfiguration'
    Properties:
      Name: 'infrastructure-configuration-name'
      InstanceProfileName: !Ref IBInstanceProfile
      Description: !Sub "ImageBuilder InfrastructureConfiguration for ${StackName}"
      InstanceTypes:
        - 't2.micro'
      KeyPair: !If [ EmptyIBKey, !Ref "AWS::NoValue", !Ref IBKeyPair]
      Logging:
        S3Logs:
          S3BucketName: !Ref BucketName
          S3KeyPrefix: 'bh-imagebuilder'
      #SnsTopicArn: !Ref SnsTopicArn
      TerminateInstanceOnFailure: true
      SecurityGroupIds:
        - !Ref SGId
      #   - 'security-group-id-2'
      SubnetId: !Ref SubnetId

  ImageRecipeAllParameters:
    Type: 'AWS::ImageBuilder::ImageRecipe'
    Properties:
      Name: 'BHImageRecipe'
      Version: '1.0.0'
      ParentImage: !FindInMap [RegionMap, !Ref "AWS::Region", ParentImage]
      Description: 'ImageRecipeAllParameters'
      Components:
         - ComponentArn: !Ref ComponentAllParameters
      # BlockDeviceMappings:
      #   - DeviceName: "device-name"
      #     VirtualName: "virtual-name"
      #     Ebs:
      #       DeleteOnTermination: true
      #       Encrypted: true
      #       Iops: 100
      #       KmsKeyId: !Ref KmsKeyId
      #       SnapshotId: "snapshot-id"
      #       VolumeType: "gp2"
      #       VolumeSize: 100

  ImagePipelineAllParameters:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: !Sub "bh_ec2_ibe-${AWS::Region}"
      Description: 'The start of the automated EC2 Image Builder'
      ImageRecipeArn: !Ref ImageRecipeAllParameters
      InfrastructureConfigurationArn: !Ref InfrastructureConfigurationAll
      #DistributionConfigurationArn: !Ref DistributionConfigurationArn
      #ImageTestsConfiguration:
        #ImageTestsEnabled: false
        #TimeoutMinutes: 90
      # Schedule:
      #   ScheduleExpression: 'cron(0 0 * * 0)'
      #   PipelineExecutionStartCondition: 'EXPRESSION_MATCH_ONLY'
      #Status: 'DISABLED'

  ComponentAllParameters:
    Type: 'AWS::ImageBuilder::Component'
    Properties:
      Name: 'BHComponent'
      Platform: 'Linux'
      Version: "1.0.0"
      Description: 'ImageBuilder Component'
      ChangeDescription: 'initial version.'
      #KmsKeyId: 'customer-kms-key-id'
      Data: |
        name: HelloWorldTestingLinuxDoc - InlineData
        description: This is hello world testing doc
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: HelloWorldStep
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Hello World! Build."
          - name: validate
            steps:
              - name: HelloWorldStep
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Hello World! Validate."
          - name: test
            steps:
              - name: HelloWorldStep
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Hello World! Test."